---
ID: "1292e12a-14ce-43eb-b6f3-8b5878b1d022"
Parent: "d3d6ae66-d778-442c-9515-275b6fa6ffc2"
Template: "d3d6ae66-d778-442c-9515-275b6fa6ffc2"
Path: /sitecore/templates/Project/Components/Portfolio Item/__Standard Values
DB: master
SharedFields:
- ID: "d4c13a2f-fc97-4a2f-9180-505fc2cbed6d"
  Hint: Portfolio Item Title
  Value: Project Name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180921T105928Z
    - ID: "277edfa3-d852-4248-8dfd-8e89d19c52db"
      Hint: Portfolio Item Short Description
      Value: <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ca6f025c-6b7b-469a-a6f8-9aaf7fd0858b"
      Hint: Portfolio Item Text
      Value: |
                <h3 class="my-3">Project Description</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <h3 class="my-3">Project Details</h3>
                <ul>
                    <li>Lorem Ipsum</li>
                    <li>Dolor Sit Amet</li>
                    <li>Consectetur</li>
                    <li>Adipiscing Elit</li>
                </ul>
        
