---
ID: "00d245fd-9b9e-44e1-af4a-8e5c6742fcce"
Parent: "bad98e0e-c1b5-4598-ac13-21b06218b30c"
Template: "85adbf5b-e836-4932-a333-fe0f9fa1ed1e"
Path: /sitecore/templates/Branches/Project
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180916T164904Z
