---
ID: "b3c626f1-4e6f-47e2-ae86-c047b9ec19bc"
Parent: "f4168c1e-1164-49a8-96ce-96e06a4ac2dc"
Template: "f4168c1e-1164-49a8-96ce-96e06a4ac2dc"
Path: /sitecore/templates/Project/Site Root/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{8DC357F4-9ECC-4B32-BE03-9ACA4B3E3559}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180821T193216Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
